name: Bicep Template Analysis

on:
  push:
  pull_request:
    paths:
      - "templates/**"
    branches:
      - main
  workflow_dispatch:

jobs:
  analyze:
    name: Analyze bicep resources
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run PSRule analysis
        uses: microsoft/ps-rule@v2.9.0
        with:
          modules: 'PSRule.Rules.Azure, PSRule.Rules.CAF'
          baseline: Azure.Default
          outputFormat: NUnit3
          outputPath: reports/analysis-results.xml
          # inputPath: templates/*.bicep

      # Publish PSRule outputs as test results
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/linux@v2
        if: always()
        with:
          job_summary: true
          files: |
            reports/analysis-results.xml
