name: Bicep Template Analysis

on:
  pull_request:
    paths:
      - "templates/**"
    branches:
      - main
  workflow_dispatch:

jobs:
  analyze:
    name: Analyze bicep resources
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bicep Build
        uses: azure/CLI@v2
        with:
          azcliversion: latest
          inlineScript: |
            az bicep build --file templates/sample.bicep --outfile sample.json 

      - name: Run PSRule analysis
        uses: microsoft/ps-rule@v2.9.0
        with:
          modules: "PSRule.Rules.Azure, PSRule.Rules.CAF"
          # baseline: Azure.Default
          outputFormat: Sarif
          outputPath: reports/ps-rule-results.sarif
          inputPath: sample.json

      - name: Upload results to security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: reports/ps-rule-results.sarif

      # - name: Publish Test Results
      #   uses: EnricoMi/publish-unit-test-result-action/linux@v2
      #   if: always()
      #   with:
      #     job_summary: true
      #     files: |
      #       reports/analysis-results.xml
